queue = {
  request = {
    queueProvider = "sqs"
    region = "us-east-1"
    receiveConfig = {
      maxMessages = 1
    }
    heartbeatConfig = {
      heartbeatInterval = 10
    }
  }
  response = {
    queueProvider = "sqs"
    region = "us-east-1"
  }
}

componentRegistry = {
  url = "https://dream-sports-labs.github.io/odin-components"
}

dsl = {
  url = "https://github.com/dream-sports-labs/odin-component-interface/releases/download"

  state = {
    provider = "S3"
    config = {
      region = "us-east-1"
      forcePathStyle = false
    }
  }

  lock = {
    provider = "redis"
    config = {
    }
  }
}

runner = {
  image = "dreamsportslabs/odin-runner:0.0.1"
  imagePullPolicy = "Always"
  resources = {
    requests = {
      cpu = "100m"
      memory = "100Mi"
      ephemeral-storage = "1Gi"
    }
    limits = {
    }
  }
  dind = {
    enabled = true
    image = "docker:dind"
    imagePullPolicy = "Always"
    resources = {
      requests = {
        cpu = "100m"
        memory = "100Mi"
        ephemeral-storage = "1Gi"
      }
      limits = {
      }
    }
  }
  env = {
    LOG_LEVEL = "DEBUG"
  }
  dockerSecrets = []
  hostVolumeMounts = []
}

discovery = {
  maxRetries = 3,
  retryIntervalSecs = 2,
  timeoutSecs = 10
}

healthcheck = {
  maxRetries = 25
  waitSeconds = 5
}
