queue = {
  request = {
    endpoint = ${?ODIN_QUEUE_REQUEST_ENDPOINT}
    queueUrl = ${?ODIN_QUEUE_REQUEST_URL}
    queueProvider = ${?ODIN_QUEUE_REQUEST_PROVIDER}
    region = ${?ODIN_QUEUE_REQUEST_REGION}
  }
  response = {
    endpoint = ${?ODIN_QUEUE_RESPONSE_ENDPOINT}
    queueUrl = ${?ODIN_QUEUE_RESPONSE_URL}
    queueProvider = ${?ODIN_QUEUE_RESPONSE_PROVIDER}
    region = ${?ODIN_QUEUE_RESPONSE_REGION}
  }
}

componentRegistry = {
  url = ${?ODIN_COMPONENT_REGISTRY_URL}
  username = ${?ODIN_COMPONENT_REGISTRY_USERNAME}
  password = ${?ODIN_COMPONENT_REGISTRY_PASSWORD}
}

dsl = {
  url = ${?ODIN_DSL_URL}
  username = ${?ODIN_DSL_USERNAME}
  password = ${?ODIN_DSL_PASSWORD}
  state = {
    config = {
      bucket = ${?ODIN_DSL_STATE_S3_BUCKET}
      endpoint = ${?ODIN_DSL_STATE_S3_ENDPOINT}
      region = ${?ODIN_DSL_STATE_S3_REGION}
      forcePathStyle = ${?ODIN_DSL_STATE_S3_FORCE_PATH_STYLE}
      credentials = {
        awsAccessKeyId = ${?ODIN_DSL_STATE_S3_AWS_ACCESS_KEY_ID}
        awsSecretAccessKey = ${?ODIN_DSL_STATE_S3_AWS_SECRET_ACCESS_KEY}
      }
    }
  }

  lock = {
    config = {
      host = ${?ODIN_DSL_LOCK_REDIS_HOST}
    }
  }
}

discovery = {
  url = ${?ODIN_DISCOVERY_URL}
}

runner = {
  image = ${?ODIN_RUNNER_IMAGE}
  resources = {
    requests = {
      cpu = ${?ODIN_RUNNER_RESOURCES_REQUESTS_CPU}
      memory = ${?ODIN_RUNNER_RESOURCES_REQUESTS_MEMORY}
      ephemeral-storage = ${?ODIN_RUNNER_RESOURCES_REQUESTS_STORAGE}
    }
    limits = {
      cpu = ${?ODIN_RUNNER_RESOURCES_LIMITS_CPU}
      memory = ${?ODIN_RUNNER_RESOURCES_LIMITS_MEMORY}
      ephemeral-storage = ${?ODIN_RUNNER_RESOURCES_LIMITS_STORAGE}
    }
  }
  dind = {
    enabled = ${?ODIN_RUNNER_DIND_ENABLED}
    image = ${?ODIN_RUNNER_DIND_IMAGE}
    resources = {
      requests = {
        cpu = ${?ODIN_RUNNER_DIND_RESOURCES_REQUESTS_CPU}
        memory = ${?ODIN_RUNNER_DIND_RESOURCES_REQUESTS_MEMORY}
        ephemeral-storage = ${?ODIN_RUNNER_DIND_RESOURCES_REQUESTS_STORAGE}
      }
      limits = {
        cpu = ${?ODIN_RUNNER_DIND_RESOURCES_LIMITS_CPU}
        memory = ${?ODIN_RUNNER_DIND_RESOURCES_LIMITS_MEMORY}
        ephemeral-storage = ${?ODIN_RUNNER_DIND_RESOURCES_LIMITS_STORAGE}
      }
    }
  }
  dockerSecrets = ${?ODIN_RUNNER_DOCKER_SECRETS}
  hostVolumeMounts = ${?ODIN_RUNNER_HOST_VOLUME_MOUNTS}
}
