queue = {
  request = {
    queueProvider = "sqs"
    region = "us-east-1"
    receiveConfig = {
      maxMessages = 1
    }
    heartbeatConfig = {
      heartbeatInterval = 10
    }
  }
  response = {
    queueProvider = "sqs"
    region = "us-east-1"
  }
}

componentRegistry = {
  url = "https://dream-sports-labs.github.io/odin-components"
}

dsl = {
  url = ""

  state = {
    provider = "S3"
    config = {
      region = "us-east-1"
    }
  }

  lock = {
    provider = "redis"
    config = {
    }
  }
}

runner = {
  image = "" // Runner image
  imagePullPolicy = "Always"
  dind = {
    enabled = true
    image = "docker:dind"
    imagePullPolicy = "Always"
  }
  env = {
    LOG_LEVEL = "DEBUG"
  }
  dockerSecrets = []
  hostVolumeMounts = []
}

discovery = {
  maxRetries = 3,
  retryIntervalSecs = 2,
  timeoutSecs = 10
}

healthcheck = {
  maxRetries = 25
  waitSeconds = 5
}
