name: CI

on:
  pull_request:
    types:
      - synchronize
      - opened
      - reopened
  push:
    branches:
      - master

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Login to docker
        uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1 # v3.5.0
        with:
          registry: ${{ vars.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up JDK 17
        uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165 # v5.0.0
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
          overwrite-settings: false

      - name: Set up QEMU
        uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # v3.6.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1

      - name: Setup helm
        uses: azure/setup-helm@1a275c3b69536ee54be43f2070a358922e12c8d4 # v4.3.1
        with:
          version: "3.8.0"

      - name: Create kind cluster
        uses: helm/kind-action@a1b0e391336a6ee6713a0583f8c6240d70863de3 # v1.12.0
        with:
          cluster_name: odin

      - name: Build runner image
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          context: ./runner
          platforms: linux/amd64
          push: false
          load: true
          tags: docker.io/dream-sports-labs/odin-runner:0.0.1
          secrets: PACKER_GITHUB_API_TOKEN=${{ secrets.PACKER_GITHUB_API_TOKEN }}

      - name: Add kind kubeconfig
        run: |
          echo "BASE64_ENCODED_KUBECONFIG=$(cat ~/.kube/config | base64 --wrap 0)" >> $GITHUB_ENV
          kind load docker-image docker.io/dream-sports-labs/odin-runner:0.0.1 --name odin

      - name: Test
        env:
          ODIN_DSL_USERNAME: ${{ secrets.ODIN_DSL_USERNAME }}
          ODIN_DSL_PASSWORD: ${{ secrets.ODIN_DSL_PASSWORD }}
          ODIN_COMPONENT_REGISTRY_PASSWORD: ${{ secrets.ODIN_COMPONENT_REGISTRY_PASSWORD }}
          ODIN_COMPONENT_REGISTRY_USERNAME: ${{ secrets.ODIN_COMPONENT_REGISTRY_USERNAME }}
          ODIN_RUNNER_IMAGE: docker.io/dream-sports-labs/odin-runner:0.0.1
        run: mvn clean verify --no-transfer-progress

      - name: Publish Test Report
        uses: dorny/test-reporter@v1.7.0
        if: success() || failure()
        with:
          name: Junit Tests
          path: "target/**/TEST-*.xml"
          reporter: java-junit

      - name: Get version from pom.xml
        id: get_version
        run: |
          PROJECT_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "PROJECT_VERSION: ${PROJECT_VERSION}"
          if [[ ${PROJECT_VERSION} != *-SNAPSHOT ]]; then
            echo "::error:Version must be suffixed with '-SNAPSHOT'. Concrete versions can only be released from master branch"
            exit 1
          fi
          echo "VERSION=$PROJECT_VERSION" >> $GITHUB_OUTPUT

      - name: Publish docker image
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ vars.DOCKER_REGISTRY }}/${{ vars.DOCKER_REPOSITORY }}:${{ steps.get_version.outputs.VERSION }}
